#!/bin/bash

awk < access.log '$9~/4[0-9][0-9]/ {print "\tURL: " $7, "\tstatus-code: " $9, "\trequest-size: " $10, "\tIP :" $1}' | sed /^$/d | sort | uniq | sort -nrk6 |sed 5q | column -t >> output4.txt